language: python
python: 
  - "2.7"
  - "3.6"
install: 
  - pip install -r requirements.txt
  - pip install future # to run tests on both py3 and py2
  - pip install pandas
  - pip install tenacity
script: "./build.sh"